// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZeQ121Saqw6gy7yDo6uTzF2IdpuMLtqY',
    appId: '1:191341514192:web:53edc93ea2413b82e8bdd5',
    messagingSenderId: '191341514192',
    projectId: 'absen-dosen',
    authDomain: 'absen-dosen.firebaseapp.com',
    storageBucket: 'absen-dosen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXRO4Ftjp_vnWL2SNgxVS2Exc82pfIEcg',
    appId: '1:191341514192:android:6e70ce162515a7d1e8bdd5',
    messagingSenderId: '191341514192',
    projectId: 'absen-dosen',
    storageBucket: 'absen-dosen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh3aliu0OHq_ZQh0r3VHLY_Ilw7mqVwBE',
    appId: '1:191341514192:ios:7ca77907c30a47e5e8bdd5',
    messagingSenderId: '191341514192',
    projectId: 'absen-dosen',
    storageBucket: 'absen-dosen.appspot.com',
    iosClientId: '191341514192-mfgou60hcs8je9t9kv9jv6df8302nu7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiAbsenDosen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh3aliu0OHq_ZQh0r3VHLY_Ilw7mqVwBE',
    appId: '1:191341514192:ios:7ca77907c30a47e5e8bdd5',
    messagingSenderId: '191341514192',
    projectId: 'absen-dosen',
    storageBucket: 'absen-dosen.appspot.com',
    iosClientId: '191341514192-mfgou60hcs8je9t9kv9jv6df8302nu7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiAbsenDosen',
  );
}
